
export const GET_AUTHOR_BLOG_LIST_SUCCESS = 'GET_AUTHOR_BLOG_LIST_SUCCESS'
export const GET_AUTHOR_BLOG_LIST_FAIL = 'GET_AUTHOR_BLOG_LIST_FAIL'

export const GET_BLOG_SUCCESS = 'GET_BLOG_SUCCESS'
export const GET_BLOG_FAIL = 'GET_BLOG_FAIL'